# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d54aa910d4cd6b95e9326a1ca4f0e4101dc43c58d032f073999807b5a62da8665a88bc2233f008bad23d7e326408ee377e8061016e9119a8ab9889fde9c07dc2

test:
  secret_key_base: 7bf6946062214b6b68c052c951f83b2ccb6b2b217fb66f34e08f055b28a99bcbb20df3c440943b9b24e4572e3048429fad14090d61d081e4c1347b9b8854e228

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
